### ISSUE TITLE
Allow "wrap" option

### ISSUE THREAD

**Issue by ingro** [coderhaoxin/react-flatpickr#11]
Hello and thanks for your work!

I'd like to use the `wrap` option but I can't figure how with the react-component.
I'm missing something or it is a feature do you plan to add in the future?

Thank you.

**Comment by coderhaoxin** [comment]
what is `wrap` option ? ((>_<))

**Comment by ingro** [comment]
Well it's specified in the options here: https://chmln.github.io/flatpickr/options/

In old docs I remember it shows the input with a calendar and a clear button, but I can't find it in the new docs :/

**Comment by jacobmischka** [comment]
It's still in the docs, the link is just broken (and all of github pages is broken right now as well).

This should be allowed in `3.2.0`, you can see it in use [on the examples page](https://github.com/coderhaoxin/react-flatpickr/blob/master/example/index.js#L36-L42).

**Comment by ingro** [comment]
Oh, thanks for the explanation and for the fix, I will try it out! :D
