### ISSUE TITLE
Locales not provided

### ISSUE THREAD

**Issue by GuillaumeT** [coderhaoxin/react-flatpickr#16]
Hi,

it would be nice to have l10n.

It has been done on one of the forks
see: https://github.com/vylum/react-flatpickr/commit/edf3af6509492cf1d392b21300bc40a6afd09808

**Comment by theseushu** [comment]
I think its better to load your i18n files with flatpickr directly
https://chmln.github.io/flatpickr/localization/#using-modules

see this, webpack will load all locale files if you use codes from that fork, I could only image other bundlers do the same
https://webpack.js.org/guides/dependency-management/#require-with-expression

**Comment by jacobmischka** [comment]
Loading the locales as mentioned above is the correct way to do this. Closing, but feel free to continue discussing.
