### ISSUE TITLE
Cannot clear date input

### ISSUE THREAD

**Issue by bendapkiewicz** [coderhaoxin/react-flatpickr#17]
It appears clearing input is possible in the `flatpickr` library but not sure it can be triggered with `react-flatpickr`. In `flatpickr`, if a `null` value is detected in `setDate` it clears out the input. However, there doesn't seem to be a way to trigger this from `react-flatpickr` seeing has how it only calls `setDate` if the date value is _not_ `null`.

Is there another way to clear the input?

**Comment by bendapkiewicz** [comment]
Nevermind, just saw 3.1.2 with this fixed.

**Comment by k-vikram** [comment]
@bendapkiewicz  It would be helpful if you could point us to the fix as it saves time searching for same issue. Thanks!!
