### ISSUE TITLE
clickOpens

### ISSUE THREAD

**Issue by edmundtfy** [coderhaoxin/react-flatpickr#19]
Flatpickr detects the initial flatpickr clickOpens state. if it's false it cannot be clicked open, as expected.
But if you change that boolean to true later, it stays unopenable. I expect to be able to couple that with my own control variable. I did check inside Chrome's React Devtools that the datetime picker option's clickOpens option really changed from false to true, so that cannot be my error

**Comment by chmln** [comment]
@edmundtfy to achieve what you want you'd have to simply add/remove event listener and execute `open()` on the instance

**Comment by jacobmischka** [comment]
All options changes are passed to flatpickr using `set()`, but flatpickr doesn't go back and bind click handlers if `clickOpens` is change with `set`.

I think that's what's happening anyway, @chmln would of course know better than me 😉. I think this is a flatpickr issue and not a react-flatpickr issue, but please let me know if I'm wrong about that.

**Comment by jacobmischka** [comment]
@edmundtfy In case you're still interested in this, here's [an example of what @chmln described](https://github.com/coderhaoxin/react-flatpickr/issues/27#issuecomment-297834403).

**Comment by jacobmischka** [comment]
Closing for now because of the reasons I mentioned above, feel free to write back if you feel it should be reopened.
