### ISSUE TITLE
Be able to disable flatpickr input

### ISSUE THREAD

**Issue by pelhage** [coderhaoxin/react-flatpickr#27]
We should be able to prevent toggling of flatpickr when `disabled` prop is passed

https://github.com/chmln/flatpickr/releases/tag/v1.7.1

**Comment by jacobmischka** [comment]
This should work right now actually, can you provide an example where it's not working?

![peek 2017-04-26 23-28](https://cloud.githubusercontent.com/assets/3939997/25468011/1e17fade-2ad8-11e7-8491-4d6ba911241b.gif)

**Comment by pelhage** [comment]
Ahh @jacobmischka I see what's going on. Passing in any additional props invalidates `disabled`

So something like this doesn't work for me:

![screen shot 2017-04-27 at 12 53 16 pm](https://cloud.githubusercontent.com/assets/4411839/25501754/a6202a76-2b48-11e7-8be3-3aa238d1592c.png)


Ideally I could view the flatpickr's current value but be unable to edit it due to `props.disabled`

![screen shot 2017-04-27 at 12 52 42 pm](https://cloud.githubusercontent.com/assets/4411839/25501726/8c1338da-2b48-11e7-845d-c4709da52c4f.png)
(would love this to be able to be disabled)

**Comment by jacobmischka** [comment]
Ah, it's because you're using `altInput`. The new input field that flatpickr creates doesn't get disabled, because the `disabled` prop is being passed to the original input field (which flatpickr has hidden).

I'm not really sure what the best way to handle this would be, react-flatpickr doesn't really have access to the input field created by flatpickr.

I think your best option if you want that level of control will probably be to not use `altInput`, but if you have an idea that would make this work cleanly I'd be happy to hear it and reopen this.

**Comment by jacobmischka** [comment]
Or you can use `clickOpens: false` and add your own open/close handler on another element, something like this:

```jsx
        <Flatpickr
          disabled
          options={{altInput: true, clickOpens: false}}
          data-enable-time
          onOpen={() => { console.info('opened') }}
          ref={fp => { this.fp = fp }}
          onChange={this.state.onChange} />
        <button type='button'
          onClick={() => { if (this.fp && this.fp.flatpickr) { this.fp.flatpickr.open() } }}>
          open
        </button>
```

![peek 2017-04-27 15-44](https://cloud.githubusercontent.com/assets/3939997/25503570/7f1bae2e-2b60-11e7-8d50-563fe65b72e5.gif)

**Comment by jacobmischka** [comment]
Unfortunately because of #19 you can't just toggle `clickOpens`, you need to add your own handler if you want to do it this way.

**Comment by RahulReddy75** [comment]
Hi, are there any update on this issue?

**Comment by jacobmischka** [comment]
No, controlling altInput is outside the scope of this package. You'll need to either stop using altInput if you want the disabled prop to work or use a custom solution like the one above. Sorry!

**Comment by RahulReddy75** [comment]
oh ok. Can you suggest alternative way to display date in more legible way? Given that ```altInput``` is disabled. If possible?

**Comment by jacobmischka** [comment]
I'd do what I did above and set clickOpens to false and add my own handler probably, or you should be able to set the regular format to be pretty and then access the flatpickr moment object to extract the date. I'm not able to provide a snippet at the moment, I'm not at a computer right now, sorry!

**Comment by RahulReddy75** [comment]
So, I fixed it by using the ```dateFormat``` to the desired output format and disabling ```altInput``` option. 
@jacobmischka  Thanks for the input.

**Comment by jacobmischka** [comment]
Glad to hear!

**Comment by s7dhansh** [comment]
https://github.com/coderhaoxin/react-flatpickr/pull/61

Will this PR resolve this issue? Or am I missing something?

**Comment by tfmertz** [comment]
I was able to solve this similar to how @s7dhansh did. But instead, just wrapping it in a new component:
```
class AltInputDatePicker extends React.Component {
  componentDidUpdate(prevProps) {
    if (prevProps.disabled !== this.props.disabled) {
      if (this.fp && this.fp.flatpickr) {
        this.fp.flatpickr.altInput.disabled = this.props.disabled;
      }
    }
  }

  render() {
    return (
      <DatePicker
        ref={(fp) => { this.fp = fp; }}
        {...this.props}
      />
    );
  }
}
```
kinda janky updating the DOM element directly, but it works without having to rewrite Flatpickr code.

**Comment by YoussefZidan** [comment]
I used this solution and worked with me
```jsx
const AppDatePicker = ({ onChange, placeholder, value, disabled }) => {
  const inputRef = useRef();
  useEffect(() => {
    inputRef.current.flatpickr.altInput.disabled = disabled;
  }, [disabled]);

  return (
    <Flatpickr
      ref={inputRef}
      style={{ marginTop: "18px" }}
      placeholder={placeholder}
      readOnly={false}
      value={value}
      className="form-control m-0"
      options={{ altInput: true, altFormat: "F j, Y", dateFormat: "Y-m-d", mode: "range" }}
      onChange={onChange}
    />
  );
};
```

**Comment by ZachSaucier** [comment]
When using a custom render function I had to use the reference to flatpickr's `input` instead:

```
useEffect(() => {
    inputRef.current.flatpickr.input.disabled = disabled;
  }, [disabled]);
```
