### ISSUE TITLE
The installation is missing the CSS files

### ISSUE THREAD

**Issue by viniciusCamargo** [coderhaoxin/react-flatpickr#28]
Hey!

I've tried to install the component but I've got an error message stating that the CSS files were missing. As a turn around I took them from the flatpickr repository.

BTW, thanks for the component, it's really handy. :smiley:

**Comment by jacobmischka** [comment]
You're supposed to import them from `flatpickr`. It's a dependency of this package, so it'll be installed as a dependency when you install `react-flatpickr`. There's an example of this in the readme.

**Comment by viniciusCamargo** [comment]
So I have to installed it separately, haven't I? I did not find this info on  the Readme though. Thanks anyway.

**Comment by jacobmischka** [comment]
If you're using npm flatpickr will automatically be installed as a dependency when you install react-flatpickr, so you shouldn't need to install anything else separately.

I just meant that in the example in the readme the css is being imported from flatpickr and not from react-flatpickr.

**Comment by jacobmischka** [comment]
Feel free to write back if you're still running into problems, I just closed it because I don't believe it's a bug.

**Comment by viniciusCamargo** [comment]
Hey @jacobmischka! But flatpickr was not installed as dependency of react-flatpickr.

**Comment by jacobmischka** [comment]
I'm not sure what to tell you about that, it's definitely a dependency. Depending on what version of npm you're using it might be located in `node_modules/react-flatpickr/node_modules/flatpickr`. But on newer npms it should be just in the project node_modules dir.

**Comment by viniciusCamargo** [comment]
That's weird, I'm using v7.6.0. And I tried to reinstall it now and everything worked as expected. Maybe it was something with my previous install. Thank you so much @jacobmischka. That's an marvelous component. :smile:

**Comment by jacobmischka** [comment]
Glad to hear it's working!

**Comment by austinjreilly** [comment]
I also had the problem of `flatpicker` being installed in `react-flatpicker/node_modules`. `rm -rf`ing `node_modules` fixed the problem, but weird that it happened to both @viniciusCamargo and I. Is there information I could provide to help troubleshoot so that this doesn't happen to others?

Also,

**Comment by jacobmischka** [comment]
Honestly I think it just depends on the black magic algorithms that npm/yarn use to dedupe, and the version of npm/yarn you're using at the time.

I think you're on the right track, and the best thing to do would just be to mention this in the readme.

Thanks for the PR by the way!
