### ISSUE TITLE
Is it possible to use an own input field like a react-toolbox input?

### ISSUE THREAD

**Issue by edhelb** [coderhaoxin/react-flatpickr#35]
hey i would like to know if it is possible to use an custom input field like a react-toolbox input field? And is it possible to format the date via react-intl? I don't know if this is too specific but would be glad to receive an answer :)

greetings

**Comment by jacobmischka** [comment]
That should be possible I think, but it will require a little bit of work. Basically what you'll want to do is create the react-flatpickr element, hide it, and then toggle it manually when the user clicks your custom input, and then listen for the flatpickr change using the `onChange` hook and update your custom input with the value, formatting it however you want.

It's possible there's an easier way, you might have better luck asking in the [base flatpickr repo](https://github.com/chmln/flatpickr), but that's what I would do!

**Comment by edhelb** [comment]
Thanks for the fast answer! I thought of this way too but I had the hope it would be possible to pass the custom input as a child. Currently I have written my own wrapper for the [base flatpickr](https://github.com/chmln/flatpickr) but it has some bugs. Maybe it is easier to fix them instead of hiding the original input.

**Comment by ryanmargheriti** [comment]
@edhelb How did you solve it in the end? Were you able to trigger the datepicker programmatically?

**Comment by heymartinadams** [comment]
I recognize the following example isn’t quite what you may be looking for, since it does away with the input field altogether and only shows the calendar. In case it’s of use, though, sharing here. Using [Preact](http://github.com/preactjs/preact/), which is similar to React:

```js
import { useRef } from 'preact/hooks'

const Component = ({ ...props }) => {
  const widgetRef = useRef(null)

  // Hide input field
  if (widgetRef.current)
    widgetRef.current?.base?.nextElementSibling?.style?.display = 'none'

  return (
    <Flatpickr
      {...{
        ref: widgetRef,
        options: {
          // Always display calendar
          inline: true
        },
      }}
    />
  )
}

export default Component
```
