### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Billy-** [coderhaoxin/react-flatpickr#44]
How are the examples viewable? I can't find them hosted anywhere, and I tried cloning but there's no facility to run a dev server?

Kind regards

**Comment by jacobmischka** [comment]
Any http server will work, you can use [http-server from npm](https://www.npmjs.com/package/http-server), [python's http.server](https://docs.python.org/3/library/http.server.html), or something like [caddy](https://caddyserver.com/).

**Comment by Billy-** [comment]
Thanks, but I am completely aware that I could have set up a local server to view the bundle.

What I am trying to say is; they should be available easily. Preferably pre-hosted ~on github pages~ somewhere. But at least have them runnable out of the box when cloned. What is the point in having them if it's a ball-ache for anyone to view them?

Most projects come with a single command to run examples locally. And/or a development set up. How do you even preview and test your changes when developing locally? And how do you expect people to contribute?

**Comment by jacobmischka** [comment]
I don't expect anything, but it's a good idea nonetheless.

**Comment by Billy-** [comment]
I didn't mean that you expected people to contribute - I meant if someone wants to contribute; how did you expect them to be able to if there's no way to run the project locally? And I'm also very curious as to how you preview your changes and test them...

Anyway, I pulled down your change, but it doesn't seem to work. Just loads up a blank page.

**Comment by Billy-** [comment]
A little documentation would go a long way...

**Comment by jacobmischka** [comment]
Whoops you were right, sorry about that! Should work now.

"No way to run the project locally"? You needed to run the `example` script, serve from the project root, and navigate to the `/examples/` route. I agree that that that could have used a little documentation, but it's relatively easy to figure out by looking at the source files. I was able to when I started contributing.

Please feel free to contribute documentation where you feel it needs it!
