### ISSUE TITLE
Changing defaultDate doesn't set the component correctly

### ISSUE THREAD

**Issue by lifzgreat** [coderhaoxin/react-flatpickr#50]
Hi! First of all, awesome job :)

The only issue I have so far is when `render()` runs, it potentially changes the value of `defaultDate`. However, that is not reflected in the component. For example, when my app first loads, `defaultDate` is blank. It then runs an ajax() call to get the last saved date and potentially updates that option. Afterwards, the component does not reflect this change even though the instance's config option is set.

**Comment by jacobmischka** [comment]
Hello! The options property `defaultDate` is not touched by this component, we just pass it along to flatpickr. If updating the property after it's instantiated isn't working, please use a `key` prop to tell react to recreate the component instead of updating it. Something like this:

```jsx
<Flatpickr key={defaultDate.toString()} options={{ defaultDate }} />
```

When the `key` prop changes, react will destroy the component and create a new one instead of updating the values, which should work for you.

**Comment by lifzgreat** [comment]
Thanks for the super fast reply! Unfortunately, doing it your way causes an error: `Uncaught TypeError: Cannot read property 'childNodes' of undefined` And that is in `focusOnDay()` 2nd line: `?
 self.days.childNodes[newIndex]`.

At any rate, I made a `ref` to the instances of the component and if the dates change, it updates them using the `setDate()` function. It's not standard React practice, but it's working.

**Comment by jacobmischka** [comment]
Hm sorry, not sure why that's happening to you, it seems to work fine for me:

![peek 2017-11-11 17-59](https://user-images.githubusercontent.com/3939997/32694616-2c92956e-c70a-11e7-84fc-2a2faa124d79.gif)

```jsx

import 'flatpickr/dist/themes/material_green.css'

import React, { Component } from 'react'
import { render } from 'react-dom'

import Flatpickr from '../lib/index.js'

class App extends Component {
  state = {
    v: '2016-01-01 01:01',
    onChange: (_, str) => {
      console.info(str)
    }
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState(state => ({
        v: state.v.replace('2016', '2017'),
        onChange: (_, str) => {
          console.info('New change handler: ', str)
        }
      }))
    }, 2000)
  }

  render() {
    const { v } = this.state

    return (
      <main>
        <Flatpickr key={v.toString()} options={{ defaultDate: v }} />
      </main>
    )
  }
}

window.init = () => {
  render(<App />, document.querySelector('#container'))
}
```

Using `setDate` would be the same thing as using a `value` prop instead and changing that, that should work as well.

**Comment by lifzgreat** [comment]
The error happened on click. But oh my...I didn't know there was a `value` prop!!! How embarrassing. I didn't see any documentation on that but I might've just missed it.

That's exactly what I needed, and it's working perfectly now. Thank you sir!

**Comment by jacobmischka** [comment]
Ha, that should probably be documented somewhere shouldn't it... Thanks for pointing that out!

**Comment by lifzgreat** [comment]
Anytime! I'm just glad it's working perfectly :)
