### ISSUE TITLE
passing style prop to the Flatpickr tag doesn't apply these styles

### ISSUE THREAD

**Issue by sharno** [coderhaoxin/react-flatpickr#52]
I tried passing a style prop that has some styling for the input of Flatpickr. But these styles doesn't apply at all

**Comment by jacobmischka** [comment]
Hm, sorry, not sure what's going on. It should definitely work.

https://www.webpackbin.com/bins/-KzHs_rfbWcctfMSt_qB

![image](https://user-images.githubusercontent.com/3939997/32987918-d0c6db50-ccbd-11e7-951c-38a5b651391c.png)

**Comment by jacobmischka** [comment]
Are you using the `altInput` flatpickr option by chance? If you are, there's no way for us to pass along your style props to the extra input element that flatpickr creates, you'll have to do it by hand. Or not use `altInput`.

**Comment by sharno** [comment]
@jacobmischka hmmm, yes I'm using `altInput` option. Didn't know it conflicts with styling. Ok will have to use separate css and style the actual `input` html element manually or stop using the `altInput`.
Thanks a lot

**Comment by jacobmischka** [comment]
Usually when using `altInput` you'll want to use an `altInputClass` and use regular CSS (or some library like emotion) to style it that way.

Good luck!
