### ISSUE TITLE
Symbol is undefined

### ISSUE THREAD

**Issue by ferhatelmas** [coderhaoxin/react-flatpickr#53]
We don't have babel in our own code so we don't add babel runtime. Then it throws Symbol error on IE11. 

Issue can be resolved by [refactoring](https://github.com/coderhaoxin/react-flatpickr/blob/master/lib/index.js#L109) `for of` loop.

**Comment by jacobmischka** [comment]
Ah, good catch. Apologies!

**Comment by jacobmischka** [comment]
Should be fixed in `3.6.3`!

**Comment by ferhatelmas** [comment]
I confirm it's fixed. Thanks a lot :heart:
