### ISSUE TITLE
Locale attribute can't be updated

### ISSUE THREAD

**Issue by fanch35000** [coderhaoxin/react-flatpickr#54]
Locale attribute can't be updated, and stay at its initial value.

Example :

<Flatpickr options={{locale: this.props.language}} />

- Initial value : this.props.language = 'en'
- Want to modify value : change language from 'en' to 'ru'
=> Flatpickr stay in 'en' despite I wanna see it in 'ru'

**Comment by jacobmischka** [comment]
You'll likely need to reinstantiate the component upon changing locales, flatpickr probably doesn't support changing it on the fly. You can trick react-flatpickr into doing this for you by providing a `key` prop and changing it when you want the component to be recreated. Something like this should work.

```jsx
import { Russian } from 'flatpickr/dist/l10n/ru.js';

const Example = () => (
    <Flatpickr key={this.props.language} options={{locale: Russian }} />
);
```

**Comment by jacobmischka** [comment]
Closing for now, please write back if you're still experiencing this issue after using the workaround above and we can reopen it.
