### ISSUE TITLE
Moving focus to a react-flatpickr component

### ISSUE THREAD

**Issue by wasabigeek** [coderhaoxin/react-flatpickr#55]
Hi, I'm currently using a two `Flatpickr` components for split Date/Time inputs, and am trying to implement the following behaviour when user selects a Date:

- the Date dropdown (calendar) is closed - 👍 
- the Time dropdown (timepicker) is opened - 👍 
- focus moves from the Date input to the Time input - 👎 not sure how to do this

I think it's because refs have to be on a DOM element, not a component? So the following doesn't work:

```javascript
handleChange(...) {
   ...
   this.dateInput.focus();
}

render() {
    return (
        <Flatpickr
            ...
            ref={input => this.dateInput = input}
        />
    );
}
```

```javascript
handleChange(...) {
   ...
   this.dateInput.focus();
}

render() {
    return (
        <span ref={input => this.dateInput = input}>
            <Flatpickr ... />
        </span>
    );
}
```

How could I achieve this? Thanks in advance!

**Comment by jacobmischka** [comment]
Hi! You should be able to get the dom element using the `node` property of the react-flatpickr ref.

So something like this should work: 

```jsx
      <main>
        <input type="text" onChange={() => { this.reactFlatpickr.node.focus(); }} />
        <Flatpickr data-enable-time className='test'
          onChange={(_, str) => {}}
          ref={reactFlatpickr => { this.reactFlatpickr = reactFlatpickr; }} />
      </main>

```

You can also get the [flatpickr instance]( https://chmln.github.io/flatpickr/instance-methods-properties-elements/) using `this.reactFlatpickr.flatpickr`!

**Comment by wasabigeek** [comment]
Thanks @jacobmischka - it works! I had to use `.flatpickr.altInput.focus()` though, as both `.node` and `.flatpickr.input` return the hidden input.

**Comment by jacobmischka** [comment]
Ah yeah, I didn't realize you were using altInput. Glad you got it working!
