### ISSUE TITLE
Trouble overriding flatpickr css classes

### ISSUE THREAD

**Issue by effinrich** [coderhaoxin/react-flatpickr#56]
Hi,
Thanks for the react-flatpickr.  It's great, but it seems certain css classes can't be overwritten.  

The following CSS has no effect on the flatpickr styles.  This should work, but does nothing.

`.flatpickr-calendar {
    border-radius: 0 !important;
    border: 0 !important;
    font-size: 16px !important;
}`

Am I missing something?

**Comment by meechanism** [comment]
Did you check your selectors? For example, the border-radius seen at the top of the calendar is actually on `.flatpickr-month`

**Comment by jacobmischka** [comment]
Sorry, closing because this is unrelated to the react wrapper I believe. Please feel free to ask in the flatpickr repo.
