### ISSUE TITLE
How to get just a timepicker? Options not working.

### ISSUE THREAD

**Issue by qodesmith** [coderhaoxin/react-flatpickr#57]
Code:
```jsx
<Flatpickr
  value={new Date()}
  options={{enableTime: true, noCalendar: true}} />
```

This still displays the calendar. Time is showing tho, so we're halfway there :)

**Comment by qodesmith** [comment]
JUST KIDDING! Turns out we had a misspelling. We were using noCalend**e**r instead of noCalend**a**r.

**Comment by jacobmischka** [comment]
Glad you figured it out!
