### ISSUE TITLE
Uncaught exception when entering gibberish in the input field

### ISSUE THREAD

**Issue by Phyks** [coderhaoxin/react-flatpickr#58]
Hi,

When putting anything (but not a valid date) in the input field and pressing "Enter", an exception is thrown in the dev console:

```
Error: Invalid date provided: toto
Stack trace:
parseDate@http://localhost:9876/main.js:80266:38
setSelectedDate@http://localhost:9876/main.js:80106:30
setDate@http://localhost:9876/main.js:80131:9
onKeyDown@http://localhost:9876/main.js:79661:17
EventListener.handleEvent*bind@http://localhost:9876/main.js:78942:9
bindEvents@http://localhost:9876/main.js:78975:13
init@http://localhost:9876/main.js:78824:9
FlatpickrInstance@http://localhost:9876/main.js:80478:5
…
```

I guess there is a check that the `value` is a correct date value here https://github.com/coderhaoxin/react-flatpickr/blob/master/lib/index.js#L74.

Thanks!

**Comment by jacobmischka** [comment]
Since the line you link to is a flatpickr call, I believe this is an issue that should be brought up in the [flatpickr library](https://github.com/chmln/flatpickr) itself. Sorry!

If I'm mistaken and it's because of an issue here please write back and I'll reopen this!

**Comment by Phyks** [comment]
Indeed, will report there.
