### ISSUE TITLE
Using rangePlugin with react-flatpickr.? 

### ISSUE THREAD

**Issue by Unsung-crusader** [coderhaoxin/react-flatpickr#59]
Is there any way I can use rangePlugin with  "react-flatpickr".?

https://chmln.github.io/flatpickr/plugins/#rangeplugin-beta

**Comment by jacobmischka** [comment]
I believe you should be able to use the `wrap` option to get this to work, similarly to [how we do it in the examples](https://github.com/coderhaoxin/react-flatpickr/blob/master/example/index.js#L53-L59). Let me know if you're unable to get it to work!

**Comment by austinjreilly** [comment]
Yes. Check out #38.

**Comment by Unsung-crusader** [comment]
@austinjreilly  Thanks for the help. It worked.

**Comment by jacobmischka** [comment]
Thanks @austinjreilly!
