### ISSUE TITLE
There is an issue with days not being in-line

### ISSUE THREAD

**Issue by touqeerkhan11** [coderhaoxin/react-flatpickr#64]
These are my package versions

flatpickr@^4.3.2:
  version "4.4.0"
  resolved "https://registry.yarnpkg.com/flatpickr/-/flatpickr-4.4.0.tgz#44410ba77fd4feb6a24fa22a14a6111efe7882cb"

react-flatpickr@^3.6.3:
  version "3.6.4"
  resolved "https://registry.yarnpkg.com/react-flatpickr/-/react-flatpickr-3.6.4.tgz#41a8406d00d787b629839ae1f5a01ed3bb6e84ac"
  dependencies:
    flatpickr "^4.3.2"
    prop-types "^15.5.10"

<img width="316" alt="screen shot 2018-03-24 at 7 55 58 pm" src="https://user-images.githubusercontent.com/14145055/37865408-cb3b7b76-2f9d-11e8-82ec-526f1b8a2aea.png">

Strangely this is not happening with flatpickr 4.3.2. Hmm any idea why?

flatpickr@^4.0.5:
  version "4.3.2"
  resolved "https://registry.yarnpkg.com/flatpickr/-/flatpickr-4.3.2.tgz#6a477043c075ef36c3ff54fadb49b936a64d635f"

react-flatpickr@3.6.3:
  version "3.6.3"
  resolved "https://registry.yarnpkg.com/react-flatpickr/-/react-flatpickr-3.6.3.tgz#a4d5ab83b2159192f3c68981e86e721bd67d562a"
  dependencies:
    flatpickr "^4.0.5"
    prop-types "^15.5.10"

**Comment by cazuba** [comment]
I had to rollback to a stable version:
```
    "react-flatpickr": "^3.2.0",
```

**Comment by jacobmischka** [comment]
Closing because it seems to be related to flatpickr itself. Feel free to write back if you're still having issues.
