### ISSUE TITLE
Need help changing dateFormat - output always the same

### ISSUE THREAD

**Issue by 3daddict** [coderhaoxin/react-flatpickr#73]
I am trying to output the date and time in this format: `2018-10-13 08:00:00`
It's my first time using react-flatpickr and with my current code no matter what I try the date is always output like this: `Fri Oct 12 2018 10:41:11 GMT-0700 (Pacific Daylight Time)`

Here is my current code:
```
import "flatpickr/dist/themes/material_green.css"

import React from "react"
import Flatpickr from "react-flatpickr"
import { Component } from "react"

class DatePicker extends Component {
  constructor() {
    super();

    this.state = {
      date: new Date()
    };
  }

  render() {
    const { date } = this.state;
    console.log("Date: ", date)
    return (
      <Flatpickr data-enable-time
        value={date}
        options={{
            enableTime: true,
            dateFormat: "Y-m-d H:i:s",
        }}
        onChange={date => { this.setState({date}) }} />
    )
  }
}

export default DatePicker;
```

Can someone please show me how to properly output the value in the format I need?

**Comment by jacobmischka** [comment]
The first argument to the onChange handler is the raw js Date object, if you want the formatted string you want to use the second argument. See [related flatpickr docs](https://flatpickr.js.org/events/)

Example:

```js
onChange={(date, dateStr) => { console.log(dateStr); }}
```

**Comment by 3daddict** [comment]
Thank you @jacobmischka I had missed that in the documentation.
Current setup outputs to: `2018-10-09 08:26:0` is there a way to make seconds always default to 00 instead of 0?

**Comment by jacobmischka** [comment]
Sure, capitalize your `s`! 🐣

https://flatpickr.js.org/formatting/#time-formatting-tokens

Gonna close, but feel free to keep writing back if there's anything else I can help with!

**Comment by 3daddict** [comment]
> Sure, capitalize your `s`! 
> 
> https://flatpickr.js.org/formatting/#time-formatting-tokens
> 
> Gonna close, but feel free to keep writing back if there's anything else I can help with!

Ah so simple! I must get better at reading the documentation. Thanks again react-flatpickr is awesome!!!
