### ISSUE TITLE
FlatPickr update to 4.5.2

### ISSUE THREAD

**Issue by cgaeta** [coderhaoxin/react-flatpickr#77]
Hello,

Thank you for your hard work! My team is struggling with some accessibility issues, and it seems some of them are resolve in FlatPickr 4.5.2. Are there any plans to update the dependency?
Thanks!

**Comment by jacobmischka** [comment]
Due to semantic versioning, you should just need to run `npm upgrade` in your own project to update to `4.5.2`. Only when Flatpickr bumps its version to 5 will we need to update the version in this package.
